---
    
- hosts: computes
  become: true
  roles:
    - { role: common }
    - { role: pbench, when: run_pbench }

- hosts: VMs
  become: true
  roles:
    - { role: common }
    - { role: pbench, when: run_pbench }
    - { role: nfv-common }
    - { role: vpp, when: routing == "vpp" }
    - { role: testpmd, when: routing == "testpmd" }
    - { role: testpmd-sriov, when: routing == "testpmd-sriov"}

- hosts: director
  become: true
  roles:
    - { role: common }
    - { role: pbench, when: run_pbench }
    - { role: pbench-trafficgen, when: run_pbench } 

