---
    
- hosts: computes
  become: true
  roles:
    - { role: pbench, when: run_pbench == "yes" }

- hosts: VMs
  become: true
  roles:
    #- { role: pbench, when: run_pbench == "yes" }
    # The following is done in cloud-init
    - { role: nfv-common }
    - { role: vpp, when: routing == "vpp" }
    - { role: testpmd, when: routing == "testpmd" }
    - { role: testpmd-sriov, when: routing == "testpmd-sriov"}

- hosts: director
  become: true
  roles:
    - { role: pbench, when: run_pbench == "yes" }
    - { role: pbench-trafficgen, when: run_pbench == "yes" } 

