---
    
- hosts: computes
  become: true
  roles:
    - { role: common }
    - { role: pbench, when: run_pbench }
    - { role: spectre }

- hosts: VMs
  become: true
  roles:
    - { role: common }
    - { role: pbench, when: run_pbench }
    - { role: kernel-update }
    - { role: nfv-common }
    - { role: kernel-bridge, when: routing == "kernel-bridge" }
    - { role: vpp, when: routing == "vpp" }
    - { role: testpmd, when: routing == "testpmd" }
    - { role: testpmd-sriov, when: routing == "testpmd-sriov"}

- hosts: trafficgen 
  become: true
  roles:
    - { role: pbench, when: run_pbench }
    - { role: pbench-trafficgen, when: exp_pbench_trafficgen } 

