---
- name: move threads 
  hosts: computes
  become: true
  tasks:
    - name: move emulator threads 
      shell: |
        cpu_list=`grep -e "^CPUAffinity=.*" /etc/systemd/system.conf | sed -e 's/CPUAffinity=//' -e 's/ /,/g'`
        if [ ! -z "$cpu_list" ]; then
          virsh_list=`virsh list| sed -e '1,2d' -e 's/\s\+/ /g' | awk -F" " '{print $2}'`
          if [ ! -z "$virsh_list" ]; then
            for vm in $virsh_list; do virsh emulatorpin $vm --cpulist $cpu_list; done
          fi
        fi
      when: repin_kvm_emulator|default(false)|bool
    - name: move pmd threads for hyper threading
      shell: |
        pmd_vm_eth0={{pmd_vm_eth0}}
        pmd_vm_eth1={{pmd_vm_eth1}}
        pmd_vm_eth2={{pmd_vm_eth2}}
        pmd_dpdk0={{pmd_dpdk0}}
        pmd_dpdk1={{pmd_dpdk1}}
        pmd_dpdk2={{pmd_dpdk2}}
        pmd_core_mask={{pmd_core_mask}}

        ovs-vsctl --no-wait set Open_vSwitch . other_config:pmd-cpu-mask=$pmd_core_mask 
        declare -a vnic
        instance=$(virsh list | grep running | awk '{print $2}')
        n=0
        for name in $(virsh dumpxml $instance | grep \/vhu | awk -F\' '{print $4}'| sed -r -n "s/.*\/(vhu.*)/\1/p"); do
          vnic[$n]=$name
          n=$((n+1))
        done
        if ((n>=1)); then
          for i in $(seq $n); do
            core_list=$(eval echo \$pmd_dpdk$((i-1)))
            if [ -z $core_list ]; then
              true
            else 
              spaced_list=$(echo $core_list | sed -e 's/,/ /g') 
              n_pmd=$(echo $spaced_list | wc -w)
              queueID=0
              mapping=""
              for pmd in ${spaced_list}; do
                mapping="$mapping,$queueID:$pmd"
                ((queueID++))
              done
              mapping=`echo $mapping | sed -e 's/^,//'`
              ovs-vsctl set Interface dpdk$((i-1)) options:n_rxq=${n_pmd} other_config:pmd-rxq-affinity=$mapping
            fi
            core_list=$(eval echo \$pmd_vm_eth$((i-1)))
            if [ -z $core_list ]; then
              true
            else
              spaced_list=$(echo $core_list | sed -e 's/,/ /g')
              n_pmd=$(echo $spaced_list | wc -w)
              queueID=0
              mapping=""
              for pmd in ${spaced_list}; do
                mapping="$mapping,$queueID:$pmd"
                ((queueID++))
              done
              mapping=`echo $mapping | sed -e 's/^,//'`
              ovs-vsctl set Interface ${vnic[((i-1))]} other_config:pmd-rxq-affinity=$mapping
            fi
          done
        fi
      when: repin_ovs_pmd|default(false)|bool
    - name: move ovs non-pmd threads
      shell: |
        hexnum=0
        for i in `grep ^CPUAffinity /etc/systemd/system.conf | awk -F= '{print $2}'`; do hexnum=$((hexnum+2**i)); done
        core_mask=$(printf "%x\n" $hexnum)
        ovs-vsctl --no-wait set Open_vSwitch . other_config:dpdk-lcore-mask=0x${core_mask}
      when: repin_ovs_nonpmd|default(false)|bool

