---
    
- hosts: VMs
  become: true
  roles:
    - { role: pbench, when: run_pbench == "yes" }
    - { role: nfv-common }
    - { role: vpp, when: routing == "vpp" }
    - { role: testpmd, when: routing != "vpp" }


