---
# Install pbench.repo
- set_fact:
    pbench_configuration_environment: "{{ cenv | default('production') }}"

- name: install optional repo
  copy: src=etc/yum.repos.d/rhel-optional.repo dest=/etc/yum.repos.d/rhel-optional.repo owner=root group=root mode=0644
     
- name: ensure we have the pbench.repo file properly in place
  template: src=etc/yum.repos.d/pbench.repo.j2 dest=/etc/yum.repos.d/pbench.repo owner=root group=root mode=0644

# Install/upgrade pbench-agent-internal RPM
- name: install the pbench-agent-internal RPM itself via dnf
  dnf: name={{ item }} state=latest
  with_items:
    - pbench-agent-internal
    - pbench-sysstat
  when: ansible_pkg_mgr == 'dnf'

- name: install the pbench-agent-internal RPM itself via yum
  yum: name={{ item }} 
  with_items:
    - pbench-agent-internal
    - pbench-sysstat
  when: ansible_pkg_mgr == 'yum'
