---
# this need to be done after pbench rpm installed
- git:
    repo: https://github.com/atheurer/pbench.git
    dest: /root/atheurer-pbench
    version: trafficgen
  become: true
- file:
    dest: /opt/pbench-agent/bench-scripts/{{item}}
    src: /root/atheurer-pbench/agent/bench-scripts/{{item}}
    state: link
  become: true
  with_items:
    - pbench-trafficgen
    - postprocess/trafficgen-postprocess 
  
