---

# this need to be done after pbench rpm installed
- name: fix kvm-spinlock & openvswitch-datalog 
  shell: |
    cd ~
    [ -d atheurer-pbench ] || git clone https://github.com/atheurer/pbench.git atheurer-pbench
    cd atheurer-pbench
    git checkout openvswitch
    git pull origin openvswitch
    cd /opt/pbench-agent/bench-scripts
    mv kvm-spinlock kvm-spinlock.orig
    ln -s ~/atheurer-pbench/agent/tool-scripts/kvm-spinlock
    cd datalog
    mv openvswitch-datalog openvswitch-datalog.orig
    ln -s ~/atheurer-pbench/agent/tool-scripts/datalog/openvswitch-datalog
- name: spectre & meltdown 
  shell: |
    if cd  /sys/kernel/debug/x86; then
      if [ {{ enable_spectre|default(false) }} = "false" ]; then
        echo 0 > pti_enabled
        echo 0 > retp_enabled
        echo 0 > ibrs_enabled
      elif dmidecode|grep Gold; then
        echo 1 > pti_enabled
        echo 1 > ibrs_enabled
        echo 0 > retp_enabled
      else
        echo 1 > pti_enabled
        echo 1 > retp_enabled
        echo 0 > ibrs_enabled 
      fi
    fi
  ignore_errors: true
