---
- name: running testpmd in screen
  shell: |
    systemctl stop vpp
    screen -X -S testpmd quit 
    myhostname={{ inventory_hostname }}
    systemctl stop NetworkManager
    hostname $myhostname
    rmmod vfio-pci vfio_iommu_type1 vfio
    modprobe vfio enable_unsafe_noiommu_mode=1
    modprobe vfio-pci

    dpdk-devbind -u 00:05.0 00:06.0 
    dpdk-devbind -b vfio-pci 00:05.0 00:06.0 
    testpmd_cmd="testpmd -l 0,2,4 --socket-mem 1024 -n 4 --proc-type auto \
                 --file-prefix pg -w 00:05.0 -w 00:06.0 \
                 --  --forward-mode=mac --eth-peer=0,{{traffic_src_mac}} --eth-peer=1,{{traffic_dst_mac}} \
                 --nb-cores=2 --nb-ports=2 --portmask=3  --auto-start \
                 --rxq=1 --txq=1 --rxd=2048 --txd=2048 >/tmp/testpmd"
    screen -dmS testpmd bash -c "$testpmd_cmd"
    sleep 1

