---
- name: config hostname and kernel bridging 
  shell: |
    myhostname={{ inventory_hostname }}
    systemctl stop NetworkManager
    hostname $myhostname
    num=$(echo $myhostname | sed -r -n "s/demo([0-9]+)/\1/p")
    dpdk-devbind -u {{dpdk_slot_1}} {{dpdk_slot_2}}
    dpdk-devbind -b {{kernel_net_driver}} {{dpdk_slot_1}} {{dpdk_slot_2}}
    ip link set up dev ens4
    ip link set up dev ens5
    yum install -y bridge-utils
    brctl addbr br1
    brctl addif br1 ens4
    brctl addif br1 ens5 
    ip link set br1 up
    /bin/true

