---
- name: update tuned and isolcpu boot parameter
  shell: |
    yum install -y screen
    yum install -y dpdk
    yum install -y dpdk-tools
    yum -y install libhugetlbfs-utils
    hugeadm --create-global-mounts
    yum remove -y tuned
    yum install -y tuned
    yum install -y tuned-profiles-cpu-partitioning
    sed -i -r '/^isolated_cores/d' /etc/tuned/cpu-partitioning-variables.conf
    echo isolated_cores=2-5 >> /etc/tuned/cpu-partitioning-variables.conf
    tuned-adm profile cpu-partitioning
    grubby --update-kernel=`grubby --default-kernel` --args="default_hugepagesz=1G hugepagesz=1G hugepages=1 isolcpus=2-5 ipv6.disable=1"
- name: reboot and get a clean start
  shell: "nohup sh -c '( sleep 5 ; shutdown -r now )' &"
  async: 0
  poll: 0
  ignore_errors: true
- name: Wait for Machine Ready
  local_action:
    module: wait_for
    host: "{{inventory_hostname}}"
    port: 22
    delay: 10
    timeout: 90

